spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/nts_ybj?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    resources:
      static-locations: classpath:/static/,classpath:/views/
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


server:
  port: 80

logging:
  level:
    com.ntsybj: debug